[book]
authors = ["lislis"]
language = "en"
src = "src"
title = "Intro to Physical Computing"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
preferred-dark-theme = "ayu"
site-url = "/workshop-intro-physical-computing/"
